apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-server-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-server
  template:
    metadata:
      labels:
        app: llm-server
    spec:
      containers:
      - name: llm-server
        image: 575108933149.dkr.ecr.ap-northeast-2.amazonaws.com/bombi/llm:7
        ports:
        - containerPort: 8080
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: "/secrets/gcp/credentials.json"
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: DB_HOST
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: DB_PORT
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: DB_PASSWORD
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: DB_NAME
        volumeMounts:
          - name: gcp-credentials
            mountPath: /secrets/gcp
            readOnly: true
      nodeSelector:
        kubernetes.io/arch: amd64
      volumes:
        - name: gcp-credentials
          secret:
            secretName: gcp-credentials

---
apiVersion: v1
kind: Service
metadata:
  name: llm-server-service
  annotiations:
    alb.ingress.kubernetes.io/healthcheck-path: /llm/base/health
spec:
  selector:
    app: llm-server
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
