apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server-dep
  labels:
    app: auth-server
spec:
  nodeSelector:        # nodeSelector should be here, at pod spec level
    kubernetes.io/arch: amd64
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      containers:
      - name: auth-server-container
        image: 575108933149.dkr.ecr.ap-northeast-2.amazonaws.com/bombi/auth:9
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: auth-server-service
spec:

  type: NodePort
  selector:
    app: auth-server
  ports:
    - nodePort: 30010
      port: 8080
      targetPort: 8080
