apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-server-dep
  labels:
    app: core-server
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app: core-server
  template:
    metadata:
      labels:
        app: core-server
    spec:
      nodeSelector:        # nodeSelector should be here, at pod spec level
        kubernetes.io/arch: amd64
      containers:
      - name: core-server-container
        image: 575108933149.dkr.ecr.ap-northeast-2.amazonaws.com/bombi/core:4
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: core-server-service
spec:
  type: NodePort
  selector:
    app: core-server
  ports:
    - nodePort: 30030
      port: 8081
      targetPort: 8081
