apiVersion: v1
kind: Service
metadata:
  name: bridge-server-service
spec:
  type: NodePort
  selector:
    app: bridge-server
  ports:
  - nodePort: 30020
    port: 8100
    targetPort: 8100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bridge-server-dep
  labels:
    app: bridge-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bridge-server
  template:
    metadata:
      labels:
        app: bridge-server
    spec:
      containers:
      - name: bridge-server
        image: 575108933149.dkr.ecr.ap-northeast-2.amazonaws.com/bombi/bridge:latest
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8100